#!/bin/bash

function usage()
{
    cat << EOF
Link files to rpm source directory.

Usage: $(basename $0) [-s] <file> [files...]

Options:
    -s:  Symlink files (default: hardlink).

EOF
}

if [ "$1" = '-s' ]; then
    symlink='-s'
    shift
fi

if (( $# == 0 )); then
    usage >&2
    exit 1
elif [ "$1" = '-h' ]; then
    usage
    exit 0
fi

destdir=$( rpm --eval %_sourcedir ) || \
    destdir='Cannot run "rpm --eval %_sourcedir"'
if [ ! -w "$destdir" ]; then
    echo "Cannot write to rpm sourcedir \"$destdir\""
    exit 1
fi

for file in "$@"; do
    path=$( readlink -fn $file)
    ln $symlink -f $path $destdir
done

